/*
 * To change this template, choose Tools | Templates
 * and open the templa

 @Override
 public int getSize() {
 throw new UnsupportedOperationException("Not supported yet.");
 }

 @Override
 public Object getElementAt(int index) {
 throw new UnsupportedOperationException("Not supported yet.");
 }

 @Override
 public void addListDataListener(ListDataListener l) {
 throw new UnsupportedOperationException("Not supported yet.");
 }

 @Override
 public void removeListDataListener(ListDataListener l) {
 throw new UnsupportedOperationException("Not supported yet.");
 }
 }e in the editor.
 */
package hu.unideb.inf.snmp_manager.forms;

import com.adventnet.snmp.mibs.MibNode;
import com.adventnet.snmp.ui.MibTree;
import com.adventnet.snmp.ui.NodeData;
import java.awt.Component;
import java.awt.Font;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTree;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.tree.DefaultTreeCellRenderer;

/**
 *
 * @author darkfalcon
 */
public class SnmpRequestDialog extends javax.swing.JDialog {

    /**
     * Creates new form SnmpRequestDialog
     */
    public SnmpRequestDialog(java.awt.Frame parent, boolean modal, MibTree mibTree) {
        super(parent, modal);
        this.mibTree = mibTree;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        snmpTree = new javax.swing.JTree(mibTree.getTree().getModel());
        jScrollPane3 = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();
        findOidButton = new javax.swing.JButton();
        findOidField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        oidLabel = new javax.swing.JLabel();
        oidField = new javax.swing.JTextField();
        addVariableButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        variableList = new javax.swing.JList();
        removeVariableButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        typeLabel = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox();
        versionLabel = new javax.swing.JLabel();
        versionCombo = new javax.swing.JComboBox();
        retriesLabel = new javax.swing.JLabel();
        timeoutLabel = new javax.swing.JLabel();
        maxRepLabel = new javax.swing.JLabel();
        retriesField = new javax.swing.JTextField();
        timeoutField = new javax.swing.JTextField();
        maxRepField = new javax.swing.JTextField();
        nonRepLabel = new javax.swing.JLabel();
        nonRepField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        sendSnmpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SNMP MIBs"));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 275));

        snmpTree.setCellRenderer(new MyToolTipTreeRenderer());
        javax.swing.ToolTipManager.sharedInstance().registerComponent(snmpTree);
        snmpTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                snmpTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(snmpTree);

        detailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Label", ""},
                {"OID", ""},
                {"Module name", ""},
                {"Syntax", ""},
                {"Access", ""},
                {"Status", ""},
                {"DefVal", ""},
                {"Indexes", ""},
                {"Description", ""}
            },
            new String [] {
                "Properties", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableColumn column = detailsTable.getColumnModel().getColumn(0);
        column.setPreferredWidth(80);
        column = detailsTable.getColumnModel().getColumn(1);
        column.setPreferredWidth(220);

        detailsTable.getColumnModel().getColumn(1).setCellRenderer(new
            MyCellRenderer());
        detailsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(detailsTable);

        findOidButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hu/unideb/inf/snmp_manager/icons/magnifier.png"))); // NOI18N
        findOidButton.setToolTipText("Find in the MIB tree");
        findOidButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findOidButtonMouseClicked(evt);
            }
        });

        findOidField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        findOidField.setPreferredSize(new java.awt.Dimension(6, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(findOidField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(findOidButton))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findOidButton)
                    .addComponent(findOidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Variables"));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 224));

        oidLabel.setText("OID:");

        oidField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        oidField.setPreferredSize(new java.awt.Dimension(6, 25));

        addVariableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hu/unideb/inf/snmp_manager/icons/add.png"))); // NOI18N
        addVariableButton.setToolTipText("Add a new variable to the request");
        addVariableButton.setPreferredSize(new java.awt.Dimension(25, 25));
        addVariableButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addVariableButtonMouseClicked(evt);
            }
        });

        variableListModel = new DefaultListModel();
        variableList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        variableList.setModel(variableListModel);
        jScrollPane2.setViewportView(variableList);

        removeVariableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hu/unideb/inf/snmp_manager/icons/delete.png"))); // NOI18N
        removeVariableButton.setToolTipText("Remove selected variable");
        removeVariableButton.setPreferredSize(new java.awt.Dimension(25, 25));
        removeVariableButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeVariableButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(oidLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(oidField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addVariableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeVariableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(oidLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addVariableButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(removeVariableButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Request Settings"));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 196));

        typeLabel.setText("Type:");

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Version 1", "Version 2c", "Version 3"}));

        versionLabel.setText("Version:");

        versionCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Get",
            "GetNext", "GetBulk", "GetSubTree", "Walk", "Set" }));

retriesLabel.setText("Retries:");

timeoutLabel.setText("Timeout:");

maxRepLabel.setText("Max Repetitions:");

nonRepLabel.setText("Non Repeaters:");

javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
jPanel3.setLayout(jPanel3Layout);
jPanel3Layout.setHorizontalGroup(
    jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRepLabel)
                    .addComponent(nonRepLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRepField)
                    .addComponent(nonRepField)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeLabel)
                    .addComponent(versionLabel)
                    .addComponent(retriesLabel)
                    .addComponent(timeoutLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeoutField)
                    .addComponent(versionCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(typeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retriesField))))
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(typeLabel)
                .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(versionLabel)
                .addComponent(versionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(retriesLabel)
                .addComponent(retriesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(timeoutLabel)
                .addComponent(timeoutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(6, 6, 6)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(maxRepLabel)
                .addComponent(maxRepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(6, 6, 6)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(nonRepLabel)
                .addComponent(nonRepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    cancelButton.setText("Cancel");
    cancelButton.setPreferredSize(new java.awt.Dimension(80, 23));

    sendSnmpButton.setText("Send");
    sendSnmpButton.setPreferredSize(new java.awt.Dimension(80, 23));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(sendSnmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sendSnmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addVariableButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVariableButtonMouseClicked
        String oid = oidField.getText();
        if (!oid.equals("")) {
            variableListModel.addElement(oid);
        }
    }//GEN-LAST:event_addVariableButtonMouseClicked

    private void removeVariableButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeVariableButtonMouseClicked
        int[] index = variableList.getSelectedIndices();
        if (index != null) {
            for (int i = (index.length - 1); i >= 0; i--) {
                variableListModel.remove(index[i]);
            }
        }
    }//GEN-LAST:event_removeVariableButtonMouseClicked

    private void findOidButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findOidButtonMouseClicked
        String key = findOidField.getText();
        if (key != null) {
        }
    }//GEN-LAST:event_findOidButtonMouseClicked

    private void snmpTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_snmpTreeValueChanged
        NodeData node = (NodeData) snmpTree.getLastSelectedPathComponent();

        try {
            MibNode mNode = node.getUserObject();
            oidField.setText(mNode.getNumberedOIDString());

            if (mNode.getLabel() != null) {
                detailsTable.getModel().setValueAt(mNode.getLabel(), 0, 1);
            } else {
                detailsTable.getModel().setValueAt("", 0, 1);
            }

            if (mNode.getNumberedOIDString() != null) {
                detailsTable.getModel().setValueAt(mNode.getNumberedOIDString(),
                        1, 1);
            } else {
                detailsTable.getModel().setValueAt("", 1, 1);
            }

            if (mNode.getModuleName() != null) {
                detailsTable.getModel().setValueAt(mNode.getModuleName(), 2, 1);
            } else {
                detailsTable.getModel().setValueAt("", 2, 1);
            }

            if (mNode.getSyntax() != null) {
                detailsTable.getModel().setValueAt(mNode.getSyntax(), 3, 1);
            } else {
                detailsTable.getModel().setValueAt("", 3, 1);
            }

            detailsTable.getModel().setValueAt(mNode.getAccess(), 4, 1);

            if (mNode.getStatus() != null) {
                detailsTable.getModel().setValueAt(mNode.getStatus(), 5, 1);
            } else {
                detailsTable.getModel().setValueAt("", 5, 1);
            }

            if (mNode.getDescription() != null) {
                detailsTable.getModel().setValueAt(mNode.getDescription(), 8, 1);
            } else {
                detailsTable.getModel().setValueAt("", 8, 1);
            }

            if (mNode.getDefval() != null) {
                detailsTable.getModel().setValueAt(mNode.getDefval(), 6, 1);
            } else {
                detailsTable.getModel().setValueAt("", 6, 1);
            }

            if (mNode.getIndexNames() != null) {
                detailsTable.getModel().setValueAt(mNode.getIndexNames(), 7, 1);
            } else {
                detailsTable.getModel().setValueAt("", 7, 1);
            }

        } catch (NullPointerException e) {
            for (int i = 0; i <= 8; i++) {
                detailsTable.getModel().setValueAt("", i, 1);
            }
            oidField.setText(null);
        }
    }//GEN-LAST:event_snmpTreeValueChanged

    //Class for add ToopTip to JTree
    private class MyToolTipTreeRenderer extends DefaultTreeCellRenderer {

        @Override
        public Component getTreeCellRendererComponent(JTree tree, Object value,
                boolean sel, boolean expanded, boolean leaf, int row,
                boolean hasFocus) {
            final Component component = super.getTreeCellRendererComponent(
                    tree, value, sel, expanded, leaf, row, hasFocus);
            NodeData data = (NodeData) value;
            MibNode node = data.getUserObject();
            String toolTip;
            try {
                toolTip = node.getNumberedOIDString();
                this.setToolTipText(toolTip);
            } catch (NullPointerException e) {
                //System.out.println(e.getMessage());
            }
            return component;
        }
    }
    
    //Class for rendering the detailTable
    private class MyCellRenderer extends JTextArea implements TableCellRenderer {

        public MyCellRenderer() {
            setLineWrap(true);
            setWrapStyleWord(true);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            String text = String.valueOf(value);
            setFont(new Font("Tahoma", Font.PLAIN, 11));
            if (text.equals("null") || value == null) {
                setText("");
            } else {
                setText(text);
            }
            setText(String.valueOf(value));
            setSize(table.getColumnModel().getColumn(column).getWidth(),
                    getPreferredSize().height);

            if (table.getRowHeight(row) != getPreferredSize().height) {
                table.setRowHeight(row, getPreferredSize().height);
            }
            return this;
        }

        //Required to Override for performance reason
        @Override
        public void validate() {
        }

        @Override
        public void revalidate() {
        }

        @Override
        public void firePropertyChange(String propertyName, Object oldValue, Object newValue) {
        }
    }
    
    private DefaultListModel variableListModel;
    private MibTree mibTree;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVariableButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTable detailsTable;
    private javax.swing.JButton findOidButton;
    private javax.swing.JTextField findOidField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField maxRepField;
    private javax.swing.JLabel maxRepLabel;
    private javax.swing.JTextField nonRepField;
    private javax.swing.JLabel nonRepLabel;
    private javax.swing.JTextField oidField;
    private javax.swing.JLabel oidLabel;
    private javax.swing.JButton removeVariableButton;
    private javax.swing.JTextField retriesField;
    private javax.swing.JLabel retriesLabel;
    private javax.swing.JButton sendSnmpButton;
    private javax.swing.JTree snmpTree;
    private javax.swing.JTextField timeoutField;
    private javax.swing.JLabel timeoutLabel;
    private javax.swing.JComboBox typeCombo;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JList variableList;
    private javax.swing.JComboBox versionCombo;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
